config/routes.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
Rails.application.routes.draw do
  resources :favorites
  resource :schedule
  resources :shopping_carts
  resources :ticket_orders
  resources :tickets
  resources :gigs
  resources :concerts
  resources :bands
  resources :venues
  resource(:sold_out_concerts, only: [:show])
  devise_for :users
  root to: "schedules#show"
end

app/models/concert.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
# == Schema Information
#
# Table name: concerts
#
#  id          :bigint           not null, primary key
#  access      :string
#  description :text
#  genre_tags  :text
#  ilk         :string
#  name        :string
#  start_time  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  venue_id    :bigint           not null
#
class Concert < ApplicationRecord
  belongs_to :venue

  has_many :gigs,
    -> { order(order: :asc) },
    dependent: :destroy,
    inverse_of: :concert

  has_many :bands, through: :gigs
  has_many :tickets, dependent: :destroy

  validates :name, presence: true

  enum ilk: {concert: "concert", meet_n_greet: "meet_n_greet", battle: "battle"}
  enum access: {general: "general", members: "members", vips: "vips"}

  def start_day
    start_time.to_date
  end

  def duration_minutes
    gigs.map(&:duration_minutes).sum
  end

  def genre_parameters
    genre_tags.split(",").map(&:parameterize).join(",")
  end

  def unsold_ticket_count
    tickets.unsold.count
  end

  def sold_out?
    unsold_ticket_count.zero?
  end

  def sell_out!
    tickets.update_all(status: :purchased, user: User.hoarder)
  end

  def find_ticket_at(row:, number:)
    tickets.find { |ticket| ticket.row == row && ticket.number == number }
  end

  def self.random_purchase_all!(min = 10, max = 30)
    Concert.find_each { |concert| concert.random_purchase!(min, max) }
  end

  def random_purchase!(min = 10, max = 30)
    purchase = rand(min..max)

    purchase.times do
      tickets.unsold.sample.update(status: :purchased, user: User.hoarder)
    end
  end

  def self.search(query)
    joins(:bands)
      .where("concerts.name ILIKE ?", "%#{query}%")
      .or(Concert.where("concerts.genre_tags ILIKE ?", "%#{query}%"))
      .or(Concert.joins(:bands).where("bands.name ILIKE ?", "%#{query}%"))
      .uniq
  end
end

app/controllers/concerts_controller.rb
#---
# Excerpted from "Modern Front-End Development for Rails, Second Edition",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material,
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose.
# Visit https://pragprog.com/titles/nrclient2 for more book information.
#---
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[show edit update destroy]

  # GET /concerts or /concerts.json
  def index
    @query = params[:query]
    @concerts = Concert.search(@query)
  end

  # GET /concerts/1 or /concerts/1.json
  def show
    if params[:inline]
      render @concert
    end
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { render @concert }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy
    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_concert
    @concert = Concert.includes(:tickets).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def concert_params
    params.require(:concert).permit(:name, :description, :start_time, :venue_id, :genre_tags, :ilk, :access)
  end
end

app/views/concerts/_concert.html.erb
<%= turbo_frame_tag(dom_id(concert)) do %>
  <article
    class="my-4"
    data-controller="concert"
    data-sold-out-data-target="concert"
    data-concert-id-value="<%= concert.id %>"
    data-concert-sold-out-value="<%= concert.sold_out? ? "true" : "false" %>"
    data-concert-tickets-remaining-value="<%= concert.unsold_ticket_count %>"
  >
      <div class="grid gap-4 grid-cols-5">
        <div class="col-span-1 text-xl">
          <%= concert.start_time.by_example("3:04 PM") %>
        </div>
        <div class="col-span-3">
          <div class="name">
            <div class="text-lg font-bold">
              <%= link_to(concert.name, concert, data: {"turbo-frame": "_top"}) %>
            </div>
          </div>
          <div class="bands">
            <%= concert.bands.map(&:name).join(", ") %>
          </div>
          <div class="genres">
            <%= concert.genre_tags.split(",").to_sentence %>
          </div>
          <div class="text-gray-500 font-bold">
            <%= concert.venue.name %>
          </div>
        </div>
        <div class="col-span-1 text-xl my-10">
          <span data-concert-target= "tickets"></span>
          <br>
          <br>
          <div class="flex">
            <% if current_user %>
              <%= link_to(
                    "Edit",
                    edit_concert_path(concert),
                    class: SimpleForm.button_class
                  ) %>
              <% if current_user.favorite(concert) %>
                <%= button_to(
                      "Unfavorite",
                      favorite_path(id: current_user.favorite(concert)),
                      method: "delete",
                      form: { data: { "turbo-frame": "favorite-concerts"}},
                      class: SimpleForm.button_class
                    ) %>
              <% else %>
                <%= button_to(
                      "Favorite",
                      favorites_path(concert_id: concert.id),
                      method: "post",
                      form: { data: { "turbo-frame": "favorite-concerts"}},
                      class: SimpleForm.button_class
                    ) %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </article>
<% end %>

app/views/concerts/_form.html.erb
<%= turbo_frame_tag(dom_id(concert)) do %>
  <%= simple_form_for(@concert) do |f| %>
    <article class="my-4">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="grid gap-4 grid-cols-6">
        <div class="col-span-2 text-xl">
          <%= f.input :start_time %>
        </div>
        <div class="col-span-3">
          <div class="name">
            <div class="text-lg font-bold">
              <%= f.input :name %>
            </div>
          </div>
          <div class="bands">
            <%= concert.bands.map(&:name).join(", ") %>
          </div>
          <div class="genres">
            <%= f.input :genre_tags %>
          </div>
          <div class="text-gray-500 font-bold">
            <%= f.association :venue %>
          </div>
        </div>
        <div class="col-span-1 text-xl my-10">
          <%= f.input :ilk, collection: Concert.ilks %>
          <%= f.input :access, collection: Concert.accesses %>
          <%= f.button :submit %>
          <%= link_to "Cancel", concert_path(@concert, inline: true), class: "#{SimpleForm.button_class} py-2 mt-4" %>
        </div>
      </div>
    </article>
  <% end %>
<% end %>

app/views/concerts/_schedule_concert.html.erb
<article class="my-4">
  <div class="grid gap-4 grid-cols-5">
    <div class="col-span-1 text-xl">
      <%= concert.start_time.by_example("3:04 PM") %>
    </div>

    <div class="col-span-3">
      <div class="name">
        <div class="text-lg font-bold">
          <%= link_to(concert.name, concert) %>
        </div>
      </div>
      <div class="bands">
        <%= concert.bands.map(&:name).join(", ") %>
      </div>
      <div class="genres">
        <%= concert.genre_tags.split(",").to_sentence %>
      </div>
      <div class="text-gray-500 font-bold">
        <%= concert.venue.name %>
      </div>
    </div>
    <div class="col-span-1 text-xl my-10">
      <% if concert.sold_out? %>
        Sold out
      <% else %>
        <%= pluralize(concert.unsold_ticket_count, "Tickets") %>
        Remaining
      <% end %>
      <br/>
      <br/>
      <div class="flex">
        <% if current_user %>
          <% if current_user.favorite(concert) %>
            <%= button_to "Remove Favorite",
                favorite_path(id: current_user.favorite(concert)),
                method: "delete",
                class: "text-lg font-bold border p-2" %>
          <% else %>
            <%= button_to "Make Favorite",
                favorites_path(concert_id: concert.id),
                method: "post",
                class: "text-lg font-bold border p-2" %>
          <% end %>
        <% end %> 
      </div>
    </div>
  </div>
</article>

app/views/concerts/_search_result.html.erb
<article class= "my-6 max-w-screen-lg">
  <div>
    <%= concert.start_time.by_example( "Jan 2 @3:04 PM") %>
    <div class= "font-bold text-xl">
      <%= link_to(concert, data: { "turbo-frame": "_top"}) do %>
        <%= highlight(concert.name, /#{query}/i) %>
      <% end %>
      <div class= "float-right">
        <% if concert.sold_out? %>
          Sold out
        <% else %>
          <%= pluralize(concert.unsold_ticket_count, "Tickets") %>
          Remaining
        <% end %>
      </div>
    </div>
    <div>
      <%= highlight(concert.bands.map(& :name).join(", "), /#{query}/i) %>
    </div>
    <div> <%= concert.genre_tags.split(",").to_sentence %></div>
    <div> <%= concert.venue.name %></div>
  </div>
</article>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Show this concert", @concert %> |
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/index.html.erb
<%= turbo_frame_tag "search-results" do %>
  <article
    class="fixed bg-gray-300 z-10
           rounded-3xl ring-4 ring-gray-800
           max-w-screen-lg w-full
           mr-20 ml-32 px-6 py-2 mt-2
           overflow-y-auto overscroll-contain"
    data-search-target="results"
    data-action="click@window->search#resetOnOutsideClick"
  >
    <div class="text-3xl font-bold text-center">Search Results</div>
    <%= render(
          partial: "concerts/search_result",
          collection: @concerts,
          as: :concert,
          locals: {query: @query}
        ) %>
  </article>
<% end %>

<%= link_to "New concert", new_concert_path %>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/show.html.erb
<h1 class="text-4xl font-bold w-auto text-center"><%= @concert.name %></h1>
<h2 class="text-2xl font-semibold">Ticket Info</h2>
<h3 class="text-xl"><%= @concert.ilk %></h3>
<h3 class="text-xl"><%= @concert.access %></h3>
<h3 class="text-xl">
  Start Date: &nbsp;
  <%= @concert.start_time.by_example("Jan 02, 2006") %>
</h3>
<h3 class="text-xl">Venue: <%= @concert.venue.name %></h3>
<h3 class="text-xl">Schedule:</h3>
<% running_time = @concert.start_time %>
<table class="table border border-black w-4/5">
  <thead>
    <tr>
      <th>Time</th>
      <th>Band</th>
      <th>Genres</th>
    </tr>
  </thead>
  <tbody>
    <% @concert.gigs.each do |gig| %>
      <tr>
        <td><%= running_time.by_example("03:04 PM") %></td>
        <td><%= gig.band.name %></td>
        <td><%= gig.band.genre_tags.split(",").join(", ") %></td>
        <% running_time += (gig.duration_minutes * 60) %>
      </tr>
    <% end %>
  </tbody>
</table>
<h2 class="text-2xl font-semibold mt-12">Tickets</h2>
<div class="concert">
  <div class="header">
    <span>Current Tickets Purchased: &nbsp;</span>
    <span>0</span>
  </div>
  <div class="header">
    <span>Current Tickets Cost: &nbsp;</span>
    <span>$0.00</span>
  </div>
  <div class="px-5 py-4 m-2 my-4 w-40 text-center text-white transition-colors duration-150 bg-gray-800 rounded-lg focus:shadow-outline hover:bg-black">
    Clear Tickets
  </div>
  <div>
    <span class="header">How many tickets would you like?</span>
    <span class="select">
      <select>
        <%= @concert.venue.seats_per_row.times do |seat| %>
          <option><%= seat + 1 %></option>
        <% end %>
      </select>
    </span>
  </div>
  <table class="table">
    <tbody>
      <% @concert.venue.rows.times do |row| %>
        <tr>
          <% @concert.venue.seats_per_row.times do |seat| %>
            <% ticket = @concert.find_ticket_at(row: row + 1, number: seat + 1) %>
            <td>
              <%= button_to(ticket_path(ticket.id), method: :patch) do %>
                <div class="<%= color_for(ticket, current_user) %> p-4 m-2 border-black border-4 button hover:bg-blue-300 text-lg">
                  <%= seat + 1 %>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="actions">
  <%= link_to("Edit", edit_concert_path(@concert)) %>
  |
  <%= link_to("Back", concerts_path) %>
</div>